### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by aaa456** [LazyAGI/LazyLLM#103]
>>> import lazyllm
>>> t = lazyllm.TrainableModule('internlm2-chat-7b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/lazyllm/module/module.py", line 382, in __init__
    self.base_model = ModelDownloader(lazyllm.config['model_source']).download(base_model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/lazyllm/components/utils/downloader/model_downloader.py", line 68, in download
    if model in model_name_mapping.keys() and self.model_source in model_name_mapping[model][['source']].keys():
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: unhashable type: 'list'

**Comment by aaa456** [comment]
if model in model_name_mapping.keys() and self.model_source in model_name_mapping[model][['source']].keys():
需要修改为
if model in model_name_mapping.keys() and self.model_source in model_name_mapping[model]['source'].keys():

**Comment by wzh1994** [comment]
This bug is already solved by https://github.com/LazyAGI/LazyLLM/pull/40 , we will update the v0.2 version within ten days, new software packages and images will be available for you to use
