### ISSUE TITLE
function call问题

### ISSUE THREAD

**Issue by Yuang-Deng** [LazyAGI/LazyLLM#389]
了解到目前使用trainablemodel时，tools选择在内部处理，使用onlinechatmodel时，tools选择交给api处理。
当自己部署模型作为api时，选择onlinechatmodel会导致报错
![image](https://github.com/user-attachments/assets/388a880c-37aa-4481-b08f-c81713451402)
看起来像是vllm部署的原因

实际工作中，一般都会私有化部署一个大模型的api，然后使用onlinechatmodel，如果部署的api不支持tools选择，那么就没法进行functioncall。是否可以在不改变已经部署大模型api的条件下，通过参数控制tools的处理逻辑呢。

**Comment by wzh1994** [comment]
这里建议使用TrainableModule部署一个大模型服务，再通过`TrainableModule().deploy_method(xx, url=xx)`去连接
