### ISSUE TITLE
[Bug] Setting “llm_chat_history”  doesn't take effect when TrainableModule is wrapped in ServerModule

### ISSUE THREAD

**Issue by SuperEver** [LazyAGI/LazyLLM#43]
## Checklist
- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

## Describe the bug
I traced the request processing, it seems in lazyllm/components/deploy/relay/server.py  `generate` function
```
if getattr(getattr(func, '_meta', func.__class__), '__enable_request__', False):
    output = func(h.make_request(input, **kw))
else:
    output = func(input, **kw)
```
As the TrainableModule's `__enable_request__` is indeed False, the keyword extraction 'h.make_request' won't be executed. Consequently, the context set by 'llm_chat_history' won't take effect.

## Reproduction
```
# coding:utf-8
import lazyllm
from lazyllm import launchers, deploy, LazyLlmRequest

# ====================================== Setting parameters:

base_model = "xxxx/internlm2-chat-20b"
deploy_config = {"launcher": launchers.slurm(partition="pat_rd", nnode=1, nproc=1, ngpus=1, sync=False), "port": 22332}


prompter = lazyllm.ChatPrompter(instruction=" 模仿孔子的说话方式进行对话")
tm = lazyllm.TrainableModule(base_model, "").prompt(prompter).deploy_method(deploy.vllm, **deploy_config)
m = lazyllm.ServerModule(tm)
m.start()


params = {
    tm._module_id: {"llm_chat_history": [["中国的首都是哪个城市", "中国的首都是北京"]]},
}


req = LazyLlmRequest(
    input="它有哪些著名的景点",
    global_parameters=params,
)

# llm_chat_history takes effect if it's sent to tm driectly
print(tm("它有哪些著名的景点", llm_chat_history=[["中国的首都是哪个城市", "中国的首都是北京"]]))

# BUG: if tm._module_id's history will not take effect 
print(m(req))
```

## Environment
> slurm 20.11.8-7.7
> vllm 0.4.3

**Comment by wzh1994** [comment]
There is indeed a bug here. For now, you can remove the condition and keep only the line `output = func(h.make_request(input, **kw))`. We will refactor the entire logic later.

**Comment by wzh1994** [comment]
I thought about it again. This is not entirely a redundant action. If `func` is an instance of `Module`, then `make_request` is necessary. Otherwise, if `func` is a regular function or a functor, it cannot handle `request`, so the `request` should be discarded. Therefore, this should be:

```
if isinstance(func, ModuleBase) or getattr(getattr(func, '_meta', func.__class__), '__enable_request__', False):
    output = func(h.make_request(input, **kw))
else:
    output = func(input, **kw)
```

however, ModuleBase is not visible here, so you can use `type(func).__name__` temporarily. We will fix it soon.

**Comment by wzh1994** [comment]
fixed by https://github.com/LazyAGI/LazyLLM/pull/40
