### ISSUE TITLE
import_module lazyllm.components.deploy.relay.server  Error: Incorrect padding

### ISSUE THREAD

**Issue by nmhjklnm** [LazyAGI/LazyLLM#44]
---
### Issue Description
---
I encountered an error while trying to import the module `lazyllm.components.deploy.relay.server` using `importlib.import_module`.

### Steps to Reproduce

1. Use the following code to attempt the import:
    ```python
    import importlib
    importlib.import_module('lazyllm.components.deploy.relay.server')
    ```

### Error Traceback

```plaintext
Error                                     Traceback (most recent call last)
Cell In[1], line 2
      1 import importlib
----> 2 importlib.import_module('lazyllm.components.deploy.relay.server')

File ~/.conda/envs/lazyllm_docs/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1006, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:688, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File ~/project/lazyllm/lazyllm/components/deploy/relay/server.py:38
     35 def load_func(f):
     36     return cloudpickle.loads(base64.b64decode(f.encode('utf-8')))
---> 38 func = load_func(args.function)
     39 if args.before_function:
     40     before_func = load_func(args.before_function)

File ~/project/lazyllm/lazyllm/components/deploy/relay/server.py:36, in load_func(f)
     35 def load_func(f):
---> 36     return cloudpickle.loads(base64.b64decode(f.encode('utf-8')))

File ~/.conda/envs/lazyllm_docs/lib/python3.10/base64.py:87, in b64decode(s, altchars, validate)
     85 if validate and not re.fullmatch(b'[A-Za-z0-9+/]*={0,2}', s):
     86     raise binascii.Error('Non-base64 digit found')
---> 87 return binascii.a2b_base64(s)

Error: Incorrect padding
```

### Additional Context

- **Python Version**: 3.10
- **Environment**: conda environment (`lazyllm_docs`)
- **Related File**: `~/project/lazyllm/lazyllm/components/deploy/relay/server.py`

The error is related to incorrect padding in a base64 encoded string used in the `load_func` function. 
This occurs at the following line in `server.py`:
```python
func = load_func(args.function)
```

**Comment by wzh1994** [comment]
`relay/server.py` is a script to start the relay service. It cannot be directly imported via lazyllm. If you want to use this script, you need to pass in `--port` and `--func`. You can refer to [RelayServer class](https://github.com/LazyAGI/LazyLLM/blob/main/lazyllm/components/deploy/relay/base.py#L47C54-L47C107) for more information.
Similarly, [finetune/alpaca-lora](https://github.com/LazyAGI/LazyLLM/tree/main/lazyllm/components/finetune/alpaca-lora) and [finetune/collie](https://github.com/LazyAGI/LazyLLM/tree/main/lazyllm/components/finetune/collie) also cannot be directly imported via lazyllm.

**Comment by nmhjklnm** [comment]
Tks for the clarity! Super helpful.
