### ISSUE TITLE
business alignment for go global

### ISSUE THREAD

**Issue by salesverse** [LazyAGI/LazyLLM#45]
hi,
I am reaching out to invite you to participate in our upcoming AGI2B streaming session on WeChat, which focuses on the AI agent business. We are planning to discuss the AI agent business landscape in America, and your insights would be incredibly valuable.

Your expertise in demoing AI products and engaging local customers in China would add great depth to our discussion. We believe that your participation would be beneficial not only for our audience but also for expanding the reach and impact of AI agent technologies.

Could you please let me know if you are available to join us? We are flexible with the scheduling and can accommodate your availability.
 my wechat: jachenms

**Comment by wzh1994** [comment]
Thank you for your invitation. LazyLLM is currently working intensively on research and development. We are sorry that we do not have time to participate in the discussion. We plan to complete the development of core functions in early August, at which time we will promote the project and conduct technical discussions. Thank you again for your invitation
