### ISSUE TITLE
Clarification on Test Durations in CI Workflow

### ISSUE THREAD

**Issue by zhiguoxu** [LazyAGI/LazyLLM#62]
**Description:**

Hi team,

I noticed that the CI workflow defined in `main.yml` for pull requests shows significant time differences between the `BasicTests` and `AdvancedTests` stages. Specifically:

- `BasicTests` takes approximately 24m 54s
- `AdvancedTests` takes approximately 28m 8s

Could someone help clarify why there is such a notable time difference between these two test stages? Are there specific tests or steps within `AdvancedTests` that inherently require more time, or is there potential for optimization?

Additionally, any insights into how we might reduce the overall testing time for both stages would be greatly appreciated.

Thank you!
<img width="637" alt="企业微信截图_375037f7-33d2-45fd-8698-90ae88068e1f" src="https://github.com/LazyAGI/LazyLLM/assets/31875256/42b68906-f275-41f0-adee-aeadaa32026f">

**Comment by wzh1994** [comment]
BasicTests defines basic test cases, including mock tests of the framework's basic capabilities, components, flows, and modules. Under normal circumstances, it should end quickly. 
StandardTest adds local model capabilities, which rely on more packages and require more resources. FullTest additionally tests the ability to use multiple frameworks for fine-tuning/inference. 
ChargeTest tests the ability to use online models.
