### ISSUE TITLE
[BUG]When switch is used in a function, an error will be reported.

### ISSUE THREAD

**Issue by shangbin-sun** [LazyAGI/LazyLLM#65]
Hi, i have a problem now. When i use `with` to create a pipeline object in a function and use the switch object in the pipeline, an error is reported that the switch object is not defined, as follows:
![image](https://github.com/LazyAGI/LazyLLM/assets/131421804/ada72d08-5483-42de-8878-b1ed5818a8e7) 

The error is as follows: 
![image](https://github.com/LazyAGI/LazyLLM/assets/131421804/8ecd4734-2b9b-4e3f-a1d7-d1657c641d9b)

But there is no problem when the pipeline is not defined in a function, as follows:
![image](https://github.com/LazyAGI/LazyLLM/assets/131421804/c359977b-0c04-4d1a-ae62-65176c909cae)

**Comment by wzh1994** [comment]
This is the same as https://github.com/LazyAGI/LazyLLM/issues/56

**Comment by wzh1994** [comment]
这个是由于python的语法导致的，locals是局部变量的拷贝，在函数中修改locals的值并不会生效，因此我们会在后续的版本中取消这一用法
