### ISSUE TITLE
toolManager input and output parameter issues

### ISSUE THREAD

**Issue by shangbin-sun** [LazyAGI/LazyLLM#85]
Hi, I found that the input and output of toolManager in lazyLLM need to be passed in the input and output results of LLM. I am confused, why does toolManager rely on these contents? Shouldn't it only accept the tool name and input parameters?
![image](https://github.com/user-attachments/assets/17048644-c368-4ac0-9072-8ddee85af8f2)
![image](https://github.com/user-attachments/assets/7141be89-9927-429c-aed7-58e6cfd42595)

**Comment by wzh1994** [comment]
1. https://github.com/LazyAGI/LazyLLM/pull/91
